# Generated by Django 5.2.7 on 2025-12-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_acctbr_lpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.DeleteModel(
            name='AcctBr',
        ),
    ]
