# Generated by Django 5.2.7 on 2025-12-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_duty_signature_delete_acctbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcemember',
            name='company',
            field=models.CharField(blank=True, choices=[('CPC-1', 'CPC-1'), ('CPC-2', 'CPC-2'), ('CPC-3', 'CPC-3'), ('CPSC', 'CPSC'), ('HQ', 'HQ'), ('Bn HQ', 'Bn HQ'), ('Ro', 'RO'), ('Mi', 'Mi'), ('AB', 'A Branch')], max_length=50, null=True),
        ),
    ]
