# Generated by Django 5.2.7 on 2025-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_forcemember_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcemember',
            name='company',
            field=models.CharField(blank=True, choices=[('CPC-1', 'CPC-1'), ('CPC-2', 'CPC-2'), ('CPC-3', 'CPC-3'), ('CPSC', 'CPSC'), ('HQ', 'HQ'), ('Bn HQ', 'Bn HQ'), ('Ro', 'RO'), ('Mi', 'Mi'), ('A Branch', 'A Branch'), ('Acct BR', 'Acct Br'), ('RAB-1 Out', 'RAB-1 Out')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forcemember',
            name='rank',
            field=models.CharField(choices=[('OTHER', '......'), ('Offr', 'Offr'), ('DAD', 'DAD'), ('SI', 'SI'), ('ASI', 'ASI'), ('Nek', 'Nek'), ('Con', 'Con'), ('Civ', 'Civ')], max_length=20),
        ),
    ]
