# Generated by Django 5.2.7 on 2025-12-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_forcemember_company_alter_forcemember_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcemember',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
