# Generated by Django 5.2.7 on 2025-12-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_forcemember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forcemember',
            name='user',
        ),
    ]
