# Generated by Django 5.2.7 on 2025-12-30 14:56

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_forcemember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_sign_image', validators=[tasks.models.validate_jpg]),
        ),
    ]
