# Generated by Django 5.2.7 on 2025-12-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_forcemember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_sign_image'),
        ),
    ]
